### ISSUE TITLE
Twilio SDK version

### ISSUE THREAD

**Issue by liran-co** [ellisio/laravel-phone#17]
Latest Twilio SDK isn't supported

ellisio/laravel-phone v3.0.3 requires twilio/sdk ~5.15.0

**Comment by ellisio** [comment]
@liran-co `v3.0.3` requires `twilio/sdk@5.15.0`. https://github.com/ellisio/laravel-phone/blob/master/composer.json#L29

If you are including the `twilio/sdk` in your project's `composer.json`, you have two options:

1. Remove the dependency from your project's `composer.json` and let this package include it for you, or
2. Pin an older version of this package via the following:

```
"require": {
  "ellisio/laravel-phone": "{PINNED_VERSION}"
}
```

Use the following for `{PINNED_VERSION}`:

- `3.0.2` for `twilio/sdk@5.13.0`
- `3.0.1` for `twilio/sdk@5.12.0`

However, I do not recommend pinning a version of this package. Instead, I would alter the version required in your `composer.json` to be `~5.15` for your `twilio/sdk` dependency so your project is compatible with all future `3.x.x` releases of this package. I will bump to `v4.0.0` when Twilio's SDK hits `v6.0.0`.

https://getcomposer.org/doc/articles/versions.md#tilde-version-range-

So you would have the following in your `composer.json`:

```
"require": {
    "twilio/sdk": "~5.15",
    "ellisio/laravel-phone": "~3.0"
}
```

This will resolve your issue, and allow you to bump your project's dependency up minor releases as this package currently requires the SDK to be `>= 5.15 and < 6.0.0`.

**Comment by ellisio** [comment]
Also, just so its public knowledge, this project builds once every 24 hours automatically. So when Twilio bumps their SDK up minor versions, that will be included in the next build of this package on Travis. I am alerted upon failed builds and can resolve any issues their SDK introduces to this package.

Travis builds: https://travis-ci.org/ellisio/laravel-phone/builds
